server:
  port: "8088"
eureka:
  instance:
    appname: "consumer"
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

spring:
  application:
    name: "consumer"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"